name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if branch is not preview
        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/preview'
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on a branch other than preview"
          exit 1
      - name: Checkout
        uses: actions/checkout@v6
      - name: Promote preview to published
        run: |
          git config --global user.email "eric.bauerfeld+pearbot@holepunch.to"
          git config --global user.name "Eric's Pearbot"
          git fetch
          git checkout -b published
          git branch --set-upstream-to=origin/published published
          git pull --rebase --prune
          git push -u -f origin published
